version: 2.1
jobs:
  test:
    parameters:
      runtest:
        type: boolean
        default: true
      coq:
        type: string
    docker:
      - image: coqorg/coq:<<parameters.coq>>
    environment:
      OPAMVERBOSE: 1
      OPAMWITHTEST: << parameters.runtest >>
      OPAMYES: true
      TERM: xterm
      PACKAGES: >
          coq-parsec
    steps:
      - checkout
      - run:
          name: Configure environment
          command: echo . ~/.profile >> $BASH_ENV
      - run:
          name: List installed packages
          command: opam list
      - run:
          name: Compile Cérès
          command: opam install ./coq-ceres.opam
      - run:
          name: Test dependants
          command: |
              for PACKAGE in $PACKAGES
              do
                DEPS_FAILED=false
                (opam depext $PACKAGE &&
                 opam install --deps-only -t $PACKAGE) || DEPS_FAILED=true
                ([ $DEPS_FAILED == false ] && opam install $PACKAGE) ||
                 echo Dependencies broken: $PACKAGE
              done

workflows:
  version: 2
  build:
    jobs:
      - test:
          coq: '8.8'
          name: 'Coq 8.8'
          runtest: false
      - test:
          coq: '8.9'
          name: 'Coq 8.9'
          runtest: false
      - test:
          coq: '8.10'
          name: 'Coq 8.10'
      - test:
          coq: '8.11'
          name: 'Coq 8.11'
      - test:
          coq: '8.12'
          name: 'Coq 8.12'
      - test:
          coq: '8.13'
          name: 'Coq 8.13'
      - test:
          coq: '8.14'
          name: 'Coq 8.14'
      - test:
          coq: '8.15'
          name: 'Coq 8.15'
      - test:
          coq: 'dev'
          name: 'Coq dev'
