defaults: &defaults
  environment:
    OPAMVERBOSE: 1
    OPAMWITHTEST: true
    OPAMYES: true
    TERM: xterm
  steps:
  - checkout
  - run:
      name: Configure environment
      command: echo . ~/.profile >> $BASH_ENV
  - run: 
      name: List installed packages
      command: opam list
  - run:
      name: Compile Cérès
      command: opam install ./coq-ceres.opam

jobs:
  coq.8.8:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.8
  coq.8.9:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.9
  coq.8.10:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.10
  coq.8.11:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.11
  coq.8.12:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.12
  coq.dev:
    <<: *defaults
    docker:
    - image: coqorg/coq:dev

workflows:
  version: 2
  build:
    jobs:
    - coq.8.8
    - coq.8.9
    - coq.8.10
    - coq.8.11
    - coq.8.12
    - coq.dev
